name: Selenium CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium:
    runs-on: ubuntu-latest

    services:
      # Start a Selenium Standalone Chrome container
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
        options: >-
          --shm-size 2g

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'  # or the version your project requires

      - name: Set up Maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run Selenium tests
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
        run: mvn test -Dselenium.url=$SELENIUM_REMOTE_URL
